const LOGIN_USER = "LOGIN_USER";
const LOGOUT_USER = "LOGOUT_USER";
const ADD_ANSWERS = "ADD_ANSWERS";
const REMOVE_ANSWERS = "REMOVE_ANSWERS"


export { LOGIN_USER, LOGOUT_USER , ADD_ANSWERS, REMOVE_ANSWERS};